### ISSUE TITLE
Add main homescreen

### ISSUE THREAD

**Issue by chandansgowda** [chandansgowda/flutter_ui_kit#2]
Currently we are hardcoding to navigate to different app templates. Have to add a screen with listview including all screens.

**Comment by AKASHANGADII** [comment]
Hey @chandansgowda
Shall I take this up ?

**Comment by chandansgowda** [comment]
Yeahh suree @AKASHANGADII 
Good luck!

**Comment by chandansgowda** [comment]
Any updates @AKASHANGADII  ??

**Comment by chandansgowda** [comment]
Done. Thanks @AKASHANGADII
