### ISSUE TITLE
Create Finance App UI 

### ISSUE THREAD

**Issue by ShivamMenda** [chandansgowda/flutter_ui_kit#8]
Replicate the following design-:

![image](https://user-images.githubusercontent.com/74780977/195286949-0f268810-3b07-4dc8-9a00-843d319fbef7.png)

**Comment by Amanpatel2002-g** [comment]
please can you assign me this. I have experience working in flutter. I can help you

**Comment by ShivamMenda** [comment]
@Amanpatel2002-g Yes please go ahead! I'll assign this to you!

**Comment by ShivamMenda** [comment]
@Amanpatel2002-g Any Update?

**Comment by SahadevaMK** [comment]
Hey @ShivamMenda 
There seems to be no update on this issue. Shall I take this up ?

**Comment by ShivamMenda** [comment]
@SahadevaMK Yes I'll assign this to you. @Amanpatel2002-g I'm sorry it's been 8 days without any reply. Im going to have to remove you from this issue.

**Comment by ShivamMenda** [comment]
@SahadevaMK Please do work on it and open a PR when ready

**Comment by SahadevaMK** [comment]
Hey @chandansgowda 
Please review my PR - #18

**Comment by chandansgowda** [comment]
Merged. Thanks
